spring:
  datasource:
    dynamic:
      primary: main
      datasource:
        main:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:31506/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
          username: root
          password: 2168230078
        second:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@10.60.20.70:1521:XE
          username: ciems
          password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-pool
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
  redis:
    database: 0
    host: 127.0.0.1
    port: 39698
    password:
    lettuce:
      shutdown-timeout: 2000 # 关闭超时时间
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1 # 连接池中的最小空闲连接
      cluster:
        # 解决连接超时问题 每30s自动刷新一次
        refresh:
          adaptive: true
          period: 30

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.caseor.boot.datasource.entity
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    # Oracle运行插入NULL
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    cache-enabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
