spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 1024MB
  main:
    lazy-initialization: true

knife4j:
  enable: true
  setting:
    enableDynamicParameter: true
